In [1]:
from sklearn.preprocessing import StandardScaler

In [2]:
data = [[0, 0], [0, 0], [1, 1], [1, 1]]

In [3]:
scaler = StandardScaler()

In [4]:
scaler.fit(data)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [31]:
scaler.mean_

array([0.5, 0.5])

In [6]:
scaler.transform(data)

array([[-1., -1.],
       [-1., -1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [7]:
scaler.transform([[2, 2]])

array([[3., 3.]])

In [18]:
class MyStandardScaler:
    def _init_(self):
        self.mean_ = None
        self.var_ = None
        
    def fit(self, data):
        self.mean_ = np.mean(data, axis = 0)
        self.var_ = np.var(data, axis = 0)
        self.std_ = np.std(data, axis = 0)
    
    def transform(self, data):
        new_data = (np.array(data)-self.mean_)/self.std_
        return new_data
    
    def fit_transform(self, data):
        self.fit(data)
        return self.transform(data)

In [9]:
import numpy as np

In [11]:
np.mean(data, axis = 0)

array([0.5, 0.5])

In [15]:
np.var(data, axis = 0)

array([0.25, 0.25])

In [17]:
(np.array(data)-scaler.mean_)/np.std(data, axis = 0)

array([[-1., -1.],
       [-1., -1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [19]:
myscaler = MyStandardScaler()

In [20]:
data

[[0, 0], [0, 0], [1, 1], [1, 1]]

In [21]:
myscaler.fit(data)

In [22]:
myscaler.mean_

array([0.5, 0.5])

In [23]:
myscaler.var_

array([0.25, 0.25])

In [24]:
myscaler.std_

array([0.5, 0.5])

In [25]:
myscaler.transform(data)

array([[-1., -1.],
       [-1., -1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [26]:
myscaler_new = MyStandardScaler()

In [27]:
myscaler_new.fit_transform(data)

array([[-1., -1.],
       [-1., -1.],
       [ 1.,  1.],
       [ 1.,  1.]])